Repository woodpecker-ci/plugin-s3, pull requests merged in 2024-06, with the labels that each got.

#9 implement optional gzip compression
  docs.md
  main.go
  plugin.go
Labels: enhancement

#188 Update docs to reflect current pipeline config
  docs.md
Labels: bug, documentation

#194 Fix typo in docker image names
  .woodpecker/publish.yml
Labels: bug
